### ISSUE TITLE
NoMethodError in KeysController#show if key is an integer

### ISSUE THREAD

**Issue by gguillotte** [example42/hdm#11]
HDM running against a new PE 2019.2.2 installation, with issue #9 resolved by PR #10.

Steps to reproduce:

1. Perform a clean install of PE 2019.2.2 and HDM on the same system.
1. Tune `puppet_enterprise::master::puppetserver::jruby_max_active_instances: 1` in `$codedir/environments/production/data/common.yaml`.
1. Open HDM.
1. Select production for "Choose the environment".
1. Select the PE master node for "Choose the node".
1. Select `puppet_enterprise::master::puppetserver::jruby_max_active_instances` as the key.

Expected behavior:

HDM displays its value (`1` in the case of this lab system).

Observed behavior:

Error:

> undefined method `gsub!' for nil:NilClass

Full function:

```
    def content_for_key(key)
      return nil unless content
      return nil unless content.has_key?(key)

      value = content[key]
      return "true" if value == true
      return "false" if value == false
      return value if value.is_a?(String)

      value_string = value.to_yaml
      value_string.gsub!("---\n", '').gsub!(/^$\n/, '')
      value_string
    end
```

Flagged line is:

```
      value_string.gsub!("---\n", '').gsub!(/^$\n/, '')
```

Rails.root:

```
/root/hdm
```

App trace:

```
app/models/hiera/read_file.rb:37:in `content_for_key'
app/models/hiera.rb:55:in `block (2 levels) in search_key'
app/models/hiera.rb:48:in `map'
app/models/hiera.rb:48:in `block in search_key'
app/models/hiera.rb:46:in `each_pair'
app/models/hiera.rb:46:in `search_key'
app/concepts/keys/operation/show.rb:28:in `node_data!'
```

Request parameters:

```
{"on"=>:member, "environment_id"=>"production", "node_id"=>"master.test.vlan", "id"=>"puppet_enterprise::master::puppetserver::jruby_max_active_instances"}
```

--

Web console output:

```
>> value

=> 1

>> value_string

=> "--- 1\n"
```

`value_string` is the result of `value.to_yaml`. If the value were a String instead of an Integer, `return value if value.is_a?(String)` would return before this.

The behavior of `Integer.to_yaml`:

```
>> 1.to_yaml

=> "--- 1\n"

>> 10.to_yaml

=> "--- 10\n"

>> "1".to_yaml

=> "--- '1'\n"
```

Since `"--- 1"` is apparently expected from `1.to_yaml`, then:

```
>> value_string.gsub!("---\n", '').gsub!(/^$\n/, '')

NoMethodError: undefined method `gsub!' for nil:NilClass
	from /root/hdm/app/models/hiera/read_file.rb:37:in `content_for_key'
```

`"---\n"` matches nothing in `"--- 1"`. `gsub!` returns `nil` if there's no match, so `nil` is also expected. We could convert the first result to a String/`.to_s`, but it feels like the integer value would still be lost unless the match itself were changed.

For reference:

```
>> content

=> {"puppet_enterprise::profile::amq::broker::heap_mb"=>"96", "puppet_enterprise::master::puppetserver::jruby_max_active_instances"=>1, "puppet_enterprise::master::puppetserver::reserved_code_cache"=>"96m", "puppet_enterprise::profile::master::java_args"=>{"Xmx"=>"384m", "Xms"=>"128m", "XX:MaxPermSize"=>"=96m", "XX:PermSize"=>"=64m", "XX:+UseG1GC"=>""}, "puppet_enterprise::profile::puppetdb::java_args"=>{"Xmx"=>"128m", "Xms"=>"64m", "XX:MaxPermSize"=>"=96m", "XX:PermSize"=>"=64m", "XX:+UseG1GC"=>""}, "puppet_enterprise::puppetdb::read_maximum_pool_size"=>4, "puppet_enterprise::puppetdb::write_maximum_pool_size"=>2, "puppet_enterprise::profile::console::java_args"=>{"Xmx"=>"128m", "Xms"=>"64m", "XX:MaxPermSize"=>"=96m", "XX:PermSize"=>"=64m", "XX:+UseG1GC"=>""}, "puppet_enterprise::trapperkeeper::database_settings::activity::maximum_pool_size"=>2, "puppet_enterprise::trapperkeeper::database_settings::classifier::maximum_pool_size"=>2, "puppet_enterprise::trapperkeeper::database_settings::rbac::maximum_pool_size"=>2, "puppet_enterprise::profile::console::delayed_job_workers"=>1, "puppet_enterprise::profile::database::shared_buffers"=>"4MB", "puppet_enterprise::profile::orchestrator::java_args"=>{"Xmx"=>"128m", "Xms"=>"128m", "XX:+UseG1GC"=>""}}
```

There are several integer values here, and they would be common in many PE installs. I'd expect any of them to fail.

Attempting to return an Integer value prevents the error when attempting to display the key's value when selecting it in HDM:

```
--- a/app/models/hiera/read_file.rb
+++ b/app/models/hiera/read_file.rb
@@ -31,7 +31,7 @@ class Hiera
       value = content[key]
       return "true" if value == true
       return "false" if value == false
-      return value if value.is_a?(String)
+      return value if value.is_a?(String) || value.is_a?(Integer)
```

But after making this change, then editing the selected value in HDM's interface (for instance from `1` to `2` in this example), HDM appends the new value to a new key in `data/common.yaml` with the same name but `.json` suffixed, instead of overwriting the existing key's value.

```
# grep -R max_active_instances $(puppet config print codedir)
...
/etc/puppetlabs/code/environments/production/data/common.yaml:puppet_enterprise::master::puppetserver::jruby_max_active_instances: 1
/etc/puppetlabs/code/environments/production/data/common.yaml:puppet_enterprise::master::puppetserver::jruby_max_active_instances.json: 2
```

**Comment by tuxmea** [comment]
Many thanks for the feedback and the issue. We will dig into it after christmas.
