### ISSUE TITLE
List of nodes should only list nodes from selected environment

### ISSUE THREAD

**Issue by tuxmea** [example42/hdm#111]
When using puppetdb, all nodes from all environments are shown.

The list of nodes should only show the ones from the selected environment.

**Comment by oneiros** [comment]
How should the fake puppet service behave?

The node yaml files in the test data all include a `env` attribute that it could filter for. This works fine, but also means each distinct node can only appear in one environment.

Furthermore, most nodes have their `env` set to `demo`, which is not an environment we have in the test data. And for most environments we do have (except `development`) there is currently not a single node.

There are two possible solutions imo:

1. Keep the old behavior and always return all nodes. That way you always have a lot of test data visible.
2. Adjust the node test data and assign nodes to one of the test data environments. This could be tedious and might even mean adding more test nodes to cater for all the different scenarios. But that way you get a more realistic behavior when developing against the fake puppet service.

What do you think?

**Comment by tuxmea** [comment]
I will change the test data, so that we have a nodes directory in each environment.
Fake puppetdb should use these nodes lists.

**Comment by tuxmea** [comment]
@oneiros I copied all node test data to all of the test environments.
I also did a first change to fakepuppetdb to read nodes from environment. But I assume that this is not yet working.

**Comment by tuxmea** [comment]
fixed
