### ISSUE TITLE
HDM needs puppet directory in app root

### ISSUE THREAD

**Issue by tuxmea** [example42/hdm#13]
Any reason why we still need this directory?
I suppose that this is a leftover from test data when building prototype.

**Comment by fernandes** [comment]
yeah, it's sort of a leftover, we can use it in case there's not PuppetDB installed, or we can just remove and make PuppetDB a requirement.

**Comment by tuxmea** [comment]
+1 for removal and PuppetDB being a hard requirement.

**Comment by tuxmea** [comment]
solved by #35
