### ISSUE TITLE
File config/credentials.yml.enc should not be in git repo?

### ISSUE THREAD

**Issue by alvagante** [example42/hdm#56]
To verify with a Rails expert:
Should file config/credentials.yml.enc be kept in the repo or removed and added to .gitignore?
It can be regenerated with rails:credentials:edit
Maybe describe in setup instructions or via the Puppet module.

**Comment by tuxmea** [comment]
Documentation needs an additional step to generate credentials.

**Comment by tuxmea** [comment]
fixed
