### ISSUE TITLE
 NoMethodError in NodesController#show if defaults is nil

### ISSUE THREAD

**Issue by gguillotte** [example42/hdm#9]
HDM running against a new PE 2019.2.2 installation.

Steps to reproduce:

1. Perform a clean install of PE 2019.2.2 and HDM on the same system. No control repo is configured, and no user code is added.
1. Open HDM.
1. Select `production` for "Choose the environment".
1. Select the PE master node for "Choose the node".

Expected behavior:

The default PE keys for that node appear.

Observed behavior:

Error:

> undefined method `has_key?' for nil:NilClass

Extracted source reported:

```
    def default_yaml_data?
      defaults.has_key?("data_hash") && defaults["data_hash"] == "yaml_data"
    end
```

Rails.root:

```
/root/hdm
```

App trace:

```
app/models/hiera/config_file.rb:15:in `default_yaml_data?'
app/models/hiera/config_file.rb:25:in `block in initialize_environments'
app/models/hiera/config_file.rb:24:in `map'
app/models/hiera/config_file.rb:24:in `initialize_environments'
app/models/hiera/config_file.rb:7:in `initialize'
app/models/hiera.rb:85:in `new'
app/models/hiera.rb:85:in `config_file'
app/models/hiera.rb:14:in `paths'
app/models/hiera.rb:27:in `all_keys'
app/concepts/nodes/operation/show.rb:21:in `node_data!'
```

Request parameters:

```
{"on"=>:member, "environment_id"=>"production", "id"=>"master.test.vlan"}
```

--

`defaults` is defined in Hiera::ConfigFile as:

```
    def defaults
      content["defaults"]
    end
```

Ruby web console inspection of `content` after the error:

```
>> content

=> {"version"=>5, "defaults"=>nil, "hierarchy"=>[{"name"=>"Per-node data (yaml version)", "path"=>"nodes/%{::trusted.certname}.yaml"}, {"name"=>"Other YAML hierarchy levels", "paths"=>["common.yaml"]}]}
```

`content` is defined in `app/models/hiera.rb`:

```
    def content
      @content ||= YAML.load(
        File.read(Pathname.new(Settings.config_dir).join(environment, "hiera.yaml"))
      )
    end
```

It reads the environment's `hiera.yaml`:

```
      @content ||= YAML.load(
        File.read(Pathname.new(Settings.config_dir).join(environment, "hiera.yaml"))
      )
```

`./code/environments/production/hiera.yaml` with comments removed:

```
---
version: 5
defaults:
hierarchy:
  - name: "Per-node data (yaml version)"
    path: "nodes/%{::trusted.certname}.yaml"
  - name: "Other YAML hierarchy levels"
    paths:
      - "common.yaml"
```

`defaults` has no value, so `nil` is expected.

`content` is consumed in `initialize_environments`:

```
    def initialize_environments
      return @environments = [] unless content.has_key?("hierarchy")
      @environments = content['hierarchy'].map do |hierarchy|
        default_data_hash = default_yaml_data? ? 'yaml_data' : nil
        Hierarchy.new(hierarchy: hierarchy, default_data_hash: default_data_hash)
      end
    end
```

So if `default_yaml_data` is truthy, return `'yaml_data'`. Otherwise, return `nil`. 

The problem appears to be that `def default_yaml_data?` attempts to use `has_key` on a `nil`-value `defaults` and fails. `def defaults` results in `nil` if `content["defaults"]` is `nil`, as it is in the above `hiera.yaml`.

Therefore, `def default_yaml_data?` should at least check if `defaults` itself is truthy/exists before attempting to use methods on it.

```
    def default_yaml_data?
      defaults && defaults.has_key?("data_hash") && defaults["data_hash"] == "yaml_data"
    end
```

**Comment by gguillotte** [comment]
I see the relevant README prerequisite, though I didn't understand it until I hit this issue.

> you must set defaults like data_hash in hiera.yaml file

This literally means that I must set _a value for [the `defaults` key](https://puppet.com/docs/puppet/latest/hiera_config_yaml_5.html#the-defaults-key)_ in `hiera.yaml` before I can use HDM.

**Comment by tuxmea** [comment]
Many thanks for the detailled issue and the solution.
